# -*- coding: utf-8 -*-
"""2. Python variables.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HIbafPsaHnAeP4tui4XrNN_s5kXA0JTA
"""

# Python variables 
# 1. Numbes 
x = 1    # int
y = 2.8  # float
z = 1j   # complex
print("Normal variable printing")
print(x)
print(y)
print(z)

print("Type conversion of python variable")
print(type(x))
print(type(y))
print(type(z))

# 2. String variable
print("Python string variable")
#Python string:
#!/usr/bin/python

str = 'Hello World!'

print (str)          # Prints complete string
print (str[0])       # Prints first character of the string
print (str[2:5])     # Prints characters starting from 3rd to 5th
print (str[2:])      # Prints string starting from 3rd character
print (str * 2)      # Prints string two times
print (str + "+ TEST line here added ") # Prints concatenated string

#3. List variable
print("Python list variable")
#!/usr/bin/python
#python lists

str = 'Hello World!'

print (str)          # Prints complete string
print (str[0])       # Prints first character of the string
print (str[2:5])     # Prints characters starting from 3rd to 5th
print (str[2:])      # Prints string starting from 3rd character
print (str * 2)      # Prints string two times
print (str + "TEST") # Prints concatenated string

#4. Python tuples
#!/usr/bin/python
print("Python tuple variable")
tuple = ( 'abcd', 786 , 2.23, 'john', 70.2  )
tinytuple = (123, 'john')

print (tuple)               # Prints the complete tuple
print (tuple[0])            # Prints first element of the tuple
print (tuple[1:3])          # Prints elements of the tuple starting from 2nd till 3rd 
print (tuple[2:])           # Prints elements of the tuple starting from 3rd element
print (tinytuple * 2)       # Prints the contents of the tuple twice
print (tuple + tinytuple)   # Prints concatenated tuples

#3. Python dictionary variable
#!/usr/bin/python
print("Python dictionary variable")
dict = {}
dict['one'] = "This is one"
dict[2]     = "This is two"

tinydict = {'name': 'john','code':6734, 'dept': 'sales'}


print (dict['one'])       # Prints value for 'one' key
print (dict[2])           # Prints value for 2 key
print (tinydict)          # Prints complete dictionary
print (tinydict.keys())   # Prints all the keys
print (tinydict.values()) # Prints all the values